# Site settings
title: OrgAnnex
email: peter@organnex.org
description: "OrgAnnex Inc is a non-profit that promotes and practices organic gardening and agriculture methods."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: redcarpet
pygments: true
permalink: title
baseurl: /
timezone: America/Denver
